---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
BASH_SHELLCHECK_ARGUMENTS: '--external-sources --format=gcc --shell=bash'
DISABLE:
  - ACTION # FIXME: Figure out why doesn't run!
  - COPYPASTE
  - EDITORCONFIG # FIXME: Figure out why not working!?
  - PYTHON
DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - REPOSITORY_DEVSKIM
FILEIO_REPORTER: true
JSON_V8R_DISABLE_ERRORS: true
LINTER_RULES_PATH: .
PYTHON_BANDIT_CONFIG_FILE: pyproject.toml
PYTHON_FLAKE8_CONFIG_FILE: tox.ini
SHOW_ELAPSED_TIME: true
