---

# Add the pre-commit badge to the README!

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending  # Replaces or checks mixed line ending.
      - id: trailing-whitespace

      # Json
      - id: check-json
      - id: pretty-format-json  # Checks that all your JSON files are pretty.

      # Python
      - id: check-ast  # Check whether files parse as valid python.
      - id: check-builtin-literals  # Require literal syntax when initializing empty or zero Python builtin types.
      - id: debug-statements  # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: name-tests-test  # Assert that files in tests/ end in _test.py, or optionally test*.py

  # General

  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes

  # Docker

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check

  # Drop until replicatedhq/dockerfilelint:166 fixed
  # - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  #   rev: v0.1.0
  #   hooks:
  #     - id: dockerfilelint
  #       stages: [commit]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.1.0
    hooks:
      - id: hadolint

  # Git

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.0
    hooks:
      - id: gitlint

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.0
    hooks:
      - id: check-github-workflows

  # Jinja

  # - repo: https://github.com/motet-a/jinjalint
  #   rev: 01e0a4d  # pre-commit support is not tagged.
  #   hooks:
  #    - id: jinjalint

  # Markdown

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.6.4
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-beautysh
          - mdformat-black
          - mdformat-config
          # - mdformat-frontmatter  # Breaks.
          - mdformat-gfm
          - mdformat-shfmt
          - mdformat-tables
          - mdformat-toc

  # Python

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry

  - repo: https://github.com/asottile/pyupgrade
    # Automatically upgrade syntax for newer versions of the language.
    rev: v2.11.0
    hooks:
      - id: pyupgrade

  # YAML

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yml]

  # Mixed

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      # - id: git-dirty  # Configure in .gitignore
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
        args: ['--external-sources', '--format=gcc', '--shell=bash']
      - id: shfmt

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        exclude: .git/COMMIT_EDITMSG

  - repo: local
    hooks:
      - id: copier-forbidden-files
        name: copier_forbidden_files
        # yamllint disable-line rule:line-length
        entry: found copier update rejection files; review them and remove them (https://copier.readthedocs.io/en/stable/updating/)
        language: fail
        files: "\\.rej$"
