# yamllint disable-line rule:document-start
name: Cron Jobs

# yamllint disable-line rule:truthy
on:
  schedule:
    # every day at midnight
    - cron: '0 0 * * *'
  # Run workflow manually (without waiting for the cron to be called),
  # through the Github Actions Workflow page directly.
  workflow_dispatch:

jobs:
  cronjobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shfmt
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install shfmt

      - name: Install hadolint
        run: |
          sudo wget --output-document /usr/bin/hadolint \
              https://github.com/hadolint/hadolint/releases/download/v2.3.0/hadolint-Linux-x86_64
          sudo chmod +x /usr/bin/hadolint

      - name: Install poetry
        run: |
          sudo python3 -m pip install poetry

      - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: 'Auto-update pre-commit hooks'
          body: Update versions of pre-commit hooks to latest version.

      - name: Mark Stale Issues
        uses: actions/stale@v3.0.18
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-close: 5
          days-before-stale: 30
          exempt-issue-labels: 'awaiting-approval'
          exempt-pr-labels: 'awaiting-approval'
          stale-issue-label: 'no-issue-activity'
          # yamllint disable-line rule:line-length
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
          stale-pr-label: 'no-pr-activity'
          # yamllint disable-line rule:line-length
          stale-pr-message: 'This pull request is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: 'no'
          max-depth: 1
