---
# files: 'directory1/directory2'

# Which of these should have stages?

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

          # Json
          - id: check-json
          - id: pretty-format-json # Checks that all your JSON files are pretty.

          # Python
          - id: check-ast # Check whether files parse as valid python.
          - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
          - id: check-docstring-first
          - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
          - id: name-tests-test # Assert that files in tests/ end in _test.py, or optionally test*.py
          - id: requirements-txt-fixer

    # General

    # - repo: https://github.com/Yelp/detect-secrets
    #   rev: v1.0.3
    #   hooks:
    #     - id: detect-secrets
    #       args: ['--baseline', '.secrets.baseline']
    #       exclude: package.lock.json

    - repo: https://github.com/sirosen/texthooks
      rev: 0.4.0
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.0
      hooks:
          - id: prettier
            stages: [commit]

    # Ansible

    - repo: https://github.com/ansible-community/ansible-lint.git
      rev: v6.5.2
      hooks:
          - id: ansible-lint
            stages:
                - commit
                - push

    # Docker

    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v2.1.0
      hooks:
          - id: docker-compose-check

    - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
          - id: dockerfilelint
            stages: [commit]

    - repo: https://github.com/hadolint/hadolint
      rev: v2.10.0
      hooks:
          - id: hadolint

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0
      hooks:
          - id: gitlint

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.32.3
      hooks:
          - id: commitizen
            stages: [commit-msg]

    # Jinja

    # - repo: https://github.com/motet-a/jinjalint
    #   rev: 01e0a4d  # pre-commit support is not tagged.
    #   hooks:
    #     - id: jinjalint

    # Markdown

    # - repo: https://github.com/executablebooks/mdformat
    #   rev: 0.7.14
    #   hooks:
    #       - id: mdformat
    #         additional_dependencies:
    #             - mdformat-beautysh
    #             - mdformat-black
    #             - mdformat-config
    #             - mdformat-deflist
    #             # - mdformat-frontmatter  # Breaks.
    #             - mdformat-footnote
    #             - mdformat-gfm
    #             - mdformat-shfmt
    #             - mdformat-tables
    #             - mdformat-toc

    # Python

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
          - id: pydocstyle

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.2.3
      hooks:
          - id: add-trailing-comma

    - repo: https://github.com/PyCQA/bandit # Add badge to README!
      rev: 1.7.4
      hooks:
          - id: bandit

    - repo: https://github.com/asottile/dead
      rev: v1.5.0
      hooks:
          - id: dead

    - repo: https://github.com/carstencodes/flake518 # Wrapper around flake8 to support pyproject.toml files.
      rev: 'v1.2.3'
      hooks:
          - id: flake518
            additional_dependencies:
                - cohesion
                - flake8-annotations-complexity
                - flake8-annotations-coverage
                - flake8-assertive
                - flake8-bandit
                - flake8-broken-line
                - flake8-bugbear
                - flake8-builtins
                - flake8-coding
                - flake8-commas
                - flake8-comprehensions
                - flake8-debugger
                - flake8-deprecated
                - flake8-docstrings
                - flake8_dodgy
                - flake8-eradicate
                - flake8-fixme
                - flake8-future-import
                - flake8-import-order
                - flake8-imports
                - flake8-isort
                - flake8-logging-format
                - flake8-mock
                - flake8-mutable
                - flake8-mypy
                - flake8-pep3101
                - flake8-print
                - flake8-pyi
                - flake8-quotes
                - flake8-spellcheck
                - flake8-strict
                - flake8-string-format
                - flake8-tidy-imports
                - flake8-variables-names
                - flake8_tuple
                - pep8-naming

    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.5
      hooks:
          - id: vulture

    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v3.0.0a5
      hooks:
          - id: pylint

    - repo: https://github.com/psf/black
      rev: 22.8.0
      hooks:
          - id: black

    - repo: https://gitlab.com/PyCQA/flake8
      rev: 3.9.2
      hooks:
          - id: flake8

    - repo: https://github.com/hadialqattan/pycln
      rev: v2.1.1 # Possible releases: https://github.com/hadialqattan/pycln/releases
      hooks:
          - id: pycln

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)

    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.3.0
      hooks:
          - id: python-safety-dependencies-check

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-blanket-type-ignore
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal
          - id: text-unicode-replacement-char

    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
          - id: check-poetry # Validates the structure of the pyproject.toml file.

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.971
      hooks:
          - id: mypy

    - repo: https://github.com/jazzband/pip-tools
      rev: 6.8.0
      hooks:
          - id: pip-compile
            files: ^requirements/production\.(in|txt)$
            args: [requirements/production.in]

    - repo: https://github.com/asottile/pyupgrade
      # Automatically upgrade syntax for newer versions of the language.
      rev: v2.37.3
      hooks:
          - id: pyupgrade
            args: [--py39-plus] # Update if I change the python3 version.

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.27.1
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    #   rev: 0.2.1
    #   hooks:
    #       - id: yamlfmt

    # SQL

    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 1.3.0
      hooks:
          - id: sqlfluff-lint
            # For dbt projects, this installs the dbt "extras".
            # You will need to select the relevant dbt adapter for your dialect
            # (https://docs.getdbt.com/docs/available-adapters):
            # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
          - id: sqlfluff-fix
            # Arbitrary arguments to show an example
            # args: [--rules, "L003,L014"]
            # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']

    # Mixed

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          # - id: bundler-audit  # FIXME: Fix ruby hooks
          # - id: check-mailmap
          # - id: fasterer
          # - id: forbid-binary
          # - id: git-check  # Configure in .gitattributes
          # - id: git-dirty  # Configure in .gitignore
          # - id: markdownlint  # Configure in .mdlrc
          # - id: reek
          # - id: require-ascii
          # - id: rubocop
          - id: script-must-have-extension
          - id: script-must-not-have-extension
          - id: shellcheck
            args: [--external-sources, --format=gcc, --shell=bash]
          - id: shfmt

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.3.1
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.18.2
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs
